### ISSUE TITLE
Display screen recommendations 

### ISSUE THREAD

**Issue by geetram** [andydoro/IMA76700-MEDP34900_Spring2018#1]
Hello, I am trying to build an interactive game with Arduino uno. I am still in the grey area when it comes to the type of display screen I should use. Should I use a LCD or an LED. Is there a specific one that could be recommended and doesn't cost a lot?

**Comment by andydoro** [comment]
hi geetram, I'd use any of the screens with a breakout here: https://www.adafruit.com/category/97

in particular, the 2.8" TFT touchscreen shield would be nice. you can use touch as an input: https://www.adafruit.com/product/1651

or, this smaller 1.8" TFT that comes with a clickable joystick, also appropriate for a game: https://www.adafruit.com/product/802
