### ISSUE TITLE
Nano sized versions of Arduino

### ISSUE THREAD

**Issue by bhurinsead** [andydoro/IMA76700-MEDP34900_Spring2018#2]
I'm looking to move from using the big Arduino UNO and putting the project (and future projects) on smaller controllers. Are there any that you would recommend and anything that I should keep in mind. 

I've been primarily looking at the Nano versions of Arduino (and all the subsequent knockoffs).

**Comment by andydoro** [comment]
for this I usually reach for a Metro Mini, which has all of the same capabilities of the Uno in a smaller form factor. other good ones to look at are also the Feathers, Itsy Bitsys and Trinkets. Some of the Trinkets have less features, however, like lack of a serial output for debugging. I sometimes use these once I've finished prototyping on a Metro Mini.
