### ISSUE TITLE
Stepper Motor

### ISSUE THREAD

**Issue by Monicar333** [andydoro/IMA76700-MEDP34900_Spring2018#3]
Is there different types of stepper motors? How would you attach something to it? Does it mater the weight you put on it? I am just not sure how it works exactly.

**Comment by andydoro** [comment]
there are different types of stepper motors, unipolar or bipolar. the "weight" is limited by the torque the stepper motor can provide. you can attach things to the axle easily if there is a notch or flat side. here is a good intro to stepper motors: https://learn.adafruit.com/all-about-stepper-motors/what-is-a-stepper-motor
