### ISSUE TITLE
Pong and Processing 

### ISSUE THREAD

**Issue by rejectedfromMIT** [andydoro/IMA76700-MEDP34900_Spring2018#4]
I would really love to figure out how to do pong using arduino and processing. I know I can do it, but I am wondering how it would work in the Arduino IDE. Do I have to install the processing library in the arduino IDE and make sure the arduino library is in the processing IDE? It would be really cool to use the POTS to move the paddles like a "joystick" on a breadboard. Is this hard? I'm looking to figure it out this weekend, perhaps.

**Comment by andydoro** [comment]
this is a classic project example from Tom Igoe's book Making Things Talk. the instructions and code for this are posted at: https://www.arduino.cc/en/Tutorial/SerialCallResponse

**Comment by geetram** [comment]
Professor Andy can you please bring me a:  2.8" TFT Touch Shield for
Arduino with Resistive Touch Screen

I will pay you back in class today. The *Elegoo EL-SM-004 UNO R3 2.8 *from
amazon still has not arrived.




Sincerely,
Geetram Hitnarine
