### ISSUE TITLE
How to center a continuous arduino?

### ISSUE THREAD

**Issue by nynz** [andydoro/IMA76700-MEDP34900_Spring2018#6]
How can I center my continuous servo so that it recenters itself at the beginning of every loop (mode the tail is in like fast wag, slow wag). Continuous servos work where 0 is counter clockwise at max speed, 90 is stop, and 180 is clockwise at max speed instead of degrees like the 180 servos. 
I can't just unscrew it and recenter it manually because I would have to do this every time I wanted to  do a different mode.

**Comment by andydoro** [comment]
Continuous servos actually lose this functionality of self-positioning. See [this description](https://learn.adafruit.com/adafruit-motor-selection-guide/continuous-rotation-servos). They are hacked servos which have gained 360 (continuous) rotation and ease of use at the expense of not being able to be positioned. If you don't need 360 motion you should use a standard servo. If you need 360 rotation and precise positioning you can use an [analog feedback servo](https://learn.adafruit.com/analog-feedback-servos).
